#!/bin/bash

mvn dependency:copy-dependencies

# Run compiled class along with classpath pointing to all the dependencies
# java -cp target/examples-1.0-SNAPSHOT.jar:target/dependency/*:target/classes 
mvn exec:java -Dexec.mainClass="ca.dimon.speculant.talibexample.KaufmanAdaptiveMovingAverageExample"
